title: Reviews
status: ready

context:
  fractal: true
  reviews:
    reviews:
      -
        comments: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        date: "5 days ago"
        rating: 4
        reviewer:
          first_name: Dan Farrow
      -
        comments: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        date: "5 days ago"
        rating: 5
        reviewer:
          first_name: Dan Farrow
      -
        comments: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        date: "5 days ago"
        rating: 4
        reviewer:
          first_name: Dan Farrow
      -
        comments: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        date: "5 days ago"
        rating: 3
        reviewer:
          first_name: Dan Farrow
      -
        comments: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        date: "5 days ago"
        rating: 5
        reviewer:
          first_name: Dan Farrow
      -
        comments: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        date: "5 days ago"
        rating: 4
        reviewer:
          first_name: Dan Farrow
      -
        comments: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        date: "5 days ago"
        rating: 5
        reviewer:
          first_name: Dan Farrow
      -
        comments: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        date: "5 days ago"
        rating: 4
        reviewer:
          first_name: Dan Farrow
      -
        comments: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        date: "5 days ago"
        rating: 5
        reviewer:
          first_name: Dan Farrow
      -
        comments: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        date: "5 days ago"
        rating: 5
        reviewer:
          first_name: Dan Farrow