title: Meet The Team
status: wip

context:
  fractal: true
  teamMembers:
    -
      team_member_image: 
        src: https://placedog.net/650/650
        title: Dan Farrow
      title: Dan Farrow
      team_member_job_title: Front-End Developer
      team_member_short_description: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis, leo non malesuada cursus, dolor erat gravida augue, in pharetra ipsum mi eu urna. Etiam eu fringilla nisl.
      team_member_telephone: 0800 000 0000
    -
      team_member_image: 
        src: https://placedog.net/650/650
        title: Dan Farrow
      title: Dan Farrow
      team_member_job_title: Front-End Developer
      team_member_short_description: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis, leo non malesuada cursus, dolor erat gravida augue, in pharetra ipsum mi eu urna. Etiam eu fringilla nisl.
      team_member_telephone: 0800 000 0000
    -
      team_member_image: 
        src: https://placedog.net/650/650
        title: Dan Farrow
      title: Dan Farrow
      team_member_job_title: Front-End Developer
      team_member_short_description: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis, leo non malesuada cursus, dolor erat gravida augue, in pharetra ipsum mi eu urna. Etiam eu fringilla nisl.
      team_member_telephone: 0800 000 0000
    -
      team_member_image: 
        src: https://placedog.net/650/650
        title: Dan Farrow
      title: Dan Farrow
      team_member_job_title: Front-End Developer
      team_member_short_description: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis, leo non malesuada cursus, dolor erat gravida augue, in pharetra ipsum mi eu urna. Etiam eu fringilla nisl.
      team_member_telephone: 0800 000 0000