title: Buckets
status: ready

context:
  fractal: true
  buckets:
    -
      thumbnail: 
        src: https://placedog.net/650/450
        title: Lovely Pooch
      post_title: <strong>Service</strong> One
      description: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      link: '#'
    -
      thumbnail: 
        src: https://placedog.net/650/450
        title: Lovely Pooch
      post_title: <strong>Service</strong> Two
      description: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      link: '#'
    -
      thumbnail: 
        src: https://placedog.net/650/450
        title: Lovely Pooch
      post_title: <strong>Service</strong> Three
      description: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      link: '#'
    -
      thumbnail: 
        src: https://placedog.net/650/450
        title: Lovely Pooch
      post_title: <strong>Service</strong> Four
      description: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      link: '#'