Title: Headers
status: ready

context:
  fractal: true
  options:
    site_logo:
      url: '#'
  topNavUsps:
    - Lorem <strong>ipsum dolor</strong> sit amet
    - <strong>Aenean eu nisi</strong> ut nulla fringilla varius
  secondaryMenu:
    items:
      -
        name: Home
        link: '#'
        current: true
        class: 'wp-classes'
      -
        name: About Us
        link: '#'
        class: 'wp-classes'
      -
        name: Meet The Team
        link: '#'
        class: 'wp-classes'
      -
        name: Gallery
        link: '#'
        class: 'wp-classes'
  primaryMenu:
    items:
      -
        name: Service One
        link: '#'
        class: 'wp-classes'
        current: true
      -
        name: Service Two
        link: '#'
        class: 'wp-classes'
        children:
          -
            name: Service Dropdown One
            link: '#'
            class: 'wp-classes'
          -
            name: Service Dropdown Two
            link: '#'
            class: 'wp-classes'
          -
            name: Service Dropdown Three
            link: '#'
            class: 'wp-classes'
      -
        name: Service Three
        link: '#'
        class: 'wp-classes'
      -
        name: Service Four
        link: '#'
        class: 'wp-classes'
      -
        name: Service Five
        link: '#'
        class: 'wp-classes'
        children:
          -
            name: Service Dropdown One
            link: '#'
            class: 'wp-classes'
          -
            name: Service Dropdown Two
            link: '#'
            class: 'wp-classes'
          -
            name: Service Dropdown Three
            link: '#'
            class: 'wp-classes'
      
