title: Why Choose Us
status: ready

context:
  whyChooseUs:
    -
      icon: https://placedog.net/650/450
      reason: Lorem <strong>ipsum dolor</strong> sit amet, <strong>consectetur</strong> adipiscing elit <strong>sit am</strong>. 
    -
      icon: https://placedog.net/650/450
      reason: Lorem <strong>ipsum dolor</strong> sit amet, <strong>consectetur</strong> adipiscing elit <strong>sit am</strong>. 
    -
      icon: https://placedog.net/650/450
      reason: Lorem <strong>ipsum dolor</strong> sit amet, <strong>consectetur</strong> adipiscing elit <strong>sit am</strong>. 
    -
      icon: https://placedog.net/650/450
      reason: Lorem <strong>ipsum dolor</strong> sit amet, <strong>consectetur</strong> adipiscing elit <strong>sit am</strong>. 
    