title: Awards & Accreditations
status: wip

context:
  accreditations:
    -
      image:
        src: https://placedog.net/650/450
        title: Logo
    -
      image: 
        src: https://placedog.net/650/450
        title: Logo
    -
      image: 
        src: https://placedog.net/650/450
        title: Logo
    -
      image: 
        src: https://placedog.net/650/450
        title: Logo
    -
      image: 
        src: https://placedog.net/650/450
        title: Logo