title: FAQs
status: ready

context:
  faqs:
    - 
      faq_question: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
      faq_answer: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet nisl eget odio lacinia, eget eleifend massa tempor. Cras ut lectus posuere, ultrices orci in, porta libero.
    - 
      faq_question: Etiam imperdiet nisl eget odio lacinia, eget eleifend massa tempor?
      faq_answer: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet nisl eget odio lacinia, eget eleifend massa tempor. Cras ut lectus posuere, ultrices orci in, porta libero.
    - 
      faq_question: Phasellus volutpat, mauris vel hendrerit pulvinar, tellus nisl volutpat lectus?
      faq_answer: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet nisl eget odio lacinia, eget eleifend massa tempor. Cras ut lectus posuere, ultrices orci in, porta libero.
    - 
      faq_question: Pellentesque habitant morbi tristique senectus et netus et malesuada?
      faq_answer: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet nisl eget odio lacinia