title: Social Media
status: ready

context:
  options:
    social_facebook: https://facebook.com/adtrak
    social_twitter: https://twitter.com/adtrak
    social_instagram: https://instagram.com/adtrak
    social_other:
      -
        name: LinkedIn
        url: https://www.linkedin.com/company/adtrak