title: Logos
status: ready

context:
  fractal: true
  header: Proud to have worked with...
  logos:
    -
      name: Logo Name
      link: https://www.adtrak.co.uk
      image: 
          url: https://placekitten.com/130/90
    -
      name: Logo Name
      image: 
          url: https://placedog.net/120/90
    -
      name: Logo Name
      link: https://www.adtrak.co.uk
      image: 
          url: https://placekitten.com/150/90
    -
      name: Logo Name
      image: 
          url: https://placedog.net/90/90
    -
      name: Logo Name
      link: https://www.adtrak.co.uk
      image: 
          url: https://placekitten.com/123/90
    -
      name: Logo Name
      image: 
          url: https://placedog.net/113/90