title: Gallery
status: ready

context:
  fractal: true
  gallery:
    -
      active: true
      url: https://placedog.net/650/450
      title: Dan Farrow
    -
      active: true
      url: https://placedog.net/650/450
      title: Dan Farrow
    -
      active: true
      url: https://placedog.net/650/450
      title: Dan Farrow
    -
      active: true
      url: https://placedog.net/650/450
      title: Dan Farrow
    -
      active: true
      url: https://placedog.net/650/450
      title: Dan Farrow