title: Branch Page
status: ready

context:
  map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2403.697404948263!2d-1.1565069840567028!3d52.95386757989864!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4879c22aaa06ec43%3A0xec466c57bd5811ae!2sAdtrak!5e0!3m2!1sen!2suk!4v1599729775665!5m2!1sen!2suk
  openingTimes:
    days:
      - 
        title: Monday
        open: 9AM
        close: 5PM
      - 
        title: Tuesday
        open: 9AM
        close: 5PM
      - 
        title: Wednesday
        open: 9AM
        close: 5PM
      - 
        title: Thursday
        open: 9AM
        close: 5PM
      - 
        title: Friday
        open: 9AM
        close: 5PM
      - 
        title: Saturday
        open: 9AM
        close: 5PM
      - 
        title: Sunday