title: Branch Page
status: ready

context:
  fractal: true
  post:
    title: Welcome to Branch Page
    content: >-
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras congue odio urna, eu pulvinar elit fermentum et. Sed convallis fringilla velit. Integer at orci at eros ullamcorper lacinia ac.</p>

      <ul>
        <li>Lorem ipsum dolor sit amet</li>
        <li>Sed nec dolor quis arcu suscipit tincidunt</li>
        <li>Fusce mi ipsum, placerat ac eros at</li>
      </ul>
      
      <p>Sed nec dolor quis arcu suscipit tincidunt. Nullam consectetur justo quis volutpat fringilla. Phasellus at lobortis metus, ac pulvinar ligula. Fusce mi ipsum, placerat ac eros at, fermentum facilisis nulla. Etiam quis dui ex.</p>

      <p>Aenean ac sem a ligula aliquam fermentum. Maecenas at felis eu tortor sodales ultricies. Praesent a pulvinar purus. Nam tincidunt facilisis lobortis.</p>
  map: <iframe class="w-full h-full" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2403.697404948263!2d-1.1565069840567028!3d52.95386757989864!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4879c22aaa06ec43%3A0xec466c57bd5811ae!2sAdtrak!5e0!3m2!1sen!2suk!4v1599729775665!5m2!1sen!2suk" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
  opening_times:
    - 
      day: Monday
      times: 9am — 5pm
    - 
      day: Tuesday
      times: 9am — 5pm
    - 
      day: Wednesday
      times: 9am — 5pm
    - 
      day: Thursday
      times: 9am — 5pm
    - 
      day: Friday
      times: 9am — 5pm
    - 
      day: Saturday
      times: Closed