title: Downloads
status: ready

context:
  downloads:
    - 
      title: Lorem ipsum dolor sit amet
      url: '#'
    - 
      title: Lorem ipsum dolor sit amet
      url: '#'
    - 
      title: Lorem ipsum dolor sit amet
      url: '#'
    - 
      title: Lorem ipsum dolor sit amet
      url: '#'