title: Projects
status: ready

context:
  fractal: true
  projects:
    - 
      title: Project 1 Title
      heading: Lorem ipsum dolor sit amet, consectetur?
      content: >-
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel diam erat. Nulla volutpat elementum velit at suscipit. Aenean tristique sed sem quis elementum. Vestibulum convallis dolor id diam vehicula, a ultricies dui accumsan. Donec ut metus iaculis, mollis ex ac, sodales felis.</p>
      gallery:
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
    - 
      title: Project 2 Title
      heading: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
      content: >-
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel diam erat. Nulla volutpat elementum velit at suscipit. Aenean tristique sed sem quis elementum. Vestibulum convallis dolor id diam vehicula, a ultricies dui accumsan. Donec ut metus iaculis, mollis ex ac, sodales felis.</p>

        <p>Morbi in condimentum massa, vitae efficitur massa. Cras vestibulum eu leo eget pharetra. In hac habitasse platea dictumst. Ut et nulla tincidunt, hendrerit ex sed.</p>
      gallery:
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
    -
      title: Project 3 Title
      heading: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
      content: >-
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel diam erat. Nulla volutpat elementum velit at suscipit. Aenean tristique sed sem quis elementum. Vestibulum convallis dolor id diam vehicula, a ultricies dui accumsan. Donec ut metus iaculis, mollis ex ac, sodales felis.</p>

        <p>Morbi in condimentum massa, vitae efficitur massa. Cras vestibulum eu leo eget pharetra. In hac habitasse platea dictumst. Ut et nulla tincidunt, hendrerit ex sed.</p>
      gallery:
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
    -
      title: Project 4 Title
      heading: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
      content: >-
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel diam erat. Nulla volutpat elementum velit at suscipit. Aenean tristique sed sem quis elementum. Vestibulum convallis dolor id diam vehicula, a ultricies dui accumsan. Donec ut metus iaculis, mollis ex ac, sodales felis.</p>

        <p>Morbi in condimentum massa, vitae efficitur massa. Cras vestibulum eu leo eget pharetra. In hac habitasse platea dictumst. Ut et nulla tincidunt, hendrerit ex sed.</p>
      gallery:
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'
        - 
          url: https://placedog.net/650/450
          alt: 'Alt tag'